apiVersion: v1
kind: Service
metadata:
  name: {{ include "litecoin.fullname" . }}
  labels:
    {{- include "litecoin.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9332
      name: rpc
    - port: 9333
      name: tcp
  clusterIP: None
  selector:
    {{- include "litecoin.selectorLabels" . | nindent 4 }}
