name: build
on:
  push:
    workflow_dispatch:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - '.github/**'
    - 'chart/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        tags: "ghcr.io/guigo2k/litecoin:0.18.1"
        load: true
        push: false

    - name: Scan Docker Image
      uses: anchore/scan-action@v3.2.0
      id: scan
      with:
        image: "ghcr.io/guigo2k/litecoin:0.18.1"
        acs-report-enable: true

    - name: Upload SARIF Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Login to GitHub Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Docker Image
      uses: docker/build-push-action@v2
      with:
        tags: "ghcr.io/guigo2k/litecoin:0.18.1"
        load: false
        push: true
